project:
  type: website
  output-dir: docs

website:
  title: "Hugo's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hugobowne
      - icon: twitter
        href: https://twitter.com/hugobowne
format:
  html:
    theme: cosmo
    css: styles.css



